### ISSUE TITLE
Could you add a "Tapped" event?

### ISSUE THREAD

**Issue by stevenbr91** [LISNR/LNRSimpleNotifications#10]
First of all, very nice library however i'm still missing a tap event when the user taps the notification.

**Comment by Jon-Schneider** [comment]
Hey Steven,

The LNRNotificationManager method ```showNotification:title:body:callback:``` has an admittedly poorly-named "callback" block parameter that is called when a user taps on your notification. I'll change that to "onTap" in the next few days when I have some time to make things clearer but it is implemented. If it doesn't quite meet your needs do you have any recommendations on what might make it more useful for you?

**Comment by stevenbr91** [comment]
Hey, thanks for the fast response, implemented & working :), used following code :
      ```
  notificationManager.showNotification(title, body: body, callback: { () -> Void in
                print("Notification tapped")
        })
```

**Comment by Jon-Schneider** [comment]
Just so you know, I updated the callback parameter name to "onTap" in version 0.4.1, which I just pushed to the spec repo a few minutes ago.
