### ISSUE TITLE
Add notifications queue

### ISSUE THREAD

**Issue by danielfmoreira** [LISNR/LNRSimpleNotifications#21]
When i receive a number of notifications simultaneously or in a short period of time, I would like them to remain in a queue.

Instead of immediately replacing each other as they get triggered, they would wait for the currently displayed notification to be dismissed.

This way all notifications can be seen and read easily by the user.

**Comment by Jon-Schneider** [comment]
Hey @danielfmoreira,

I just made an update that adds notification queueing via a __LNRNotificationQueue__ object that handles the queuing for a Notification Manager. Would you mind checking it out and letting me know what you think?
