### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by resand** [LISNR/LNRSimpleNotifications#25]
when will i have support for swift 4?

**Comment by Jon-Schneider** [comment]
I just committed an update to Swift 4, but I can't push the Pod until I get Trunk ownership moved to me (I'm not longer at my old company, but I'm still a maintainer). For now it will work with Carthage or direct source inclusion.

**Comment by resand** [comment]
I understand, thank you!

**Comment by Jon-Schneider** [comment]
0.7.0 is now available on Cocoapods.

**Comment by resand** [comment]
nice! 👍🏼
