### ISSUE TITLE
Verision 0.7.0 has not been released

### ISSUE THREAD

**Issue by dkk** [LISNR/LNRSimpleNotifications#27]
It seems the version is not included in https://github.com/CocoaPods/Specs/tree/master/Specs/e/4/1/LNRSimpleNotifications either. So I guess it is not me.

`pod search LNRSimpleNotifications` (after repo update) will show the output:

   
```
-> LNRSimpleNotifications (0.6.1)
   Simple Swift in-app notifications.
   pod 'LNRSimpleNotifications', '~> 0.6.1'
   - Homepage: https://github.com/LISNR/LNRSimpleNotifications
   - Source:   https://github.com/LISNR/LNRSimpleNotifications.git
   - Versions: 0.6.1, 0.6.0, 0.5.3, 0.5.2, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0 [master
   repo]
```

I think nobody executed `pod trunk push LNRSimpleNotifications.podspec`. For more information see https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by Jon-Schneider** [comment]
Done. There was some miscommunications about pod ownership and I wasn't able to push.
