### ISSUE TITLE
There doesn't seem to be a pod file for the example app in the repo.

### ISSUE THREAD

**Issue by AppleWatchHipster** [LISNR/LNRSimpleNotifications#9]
Nice library BTW 

The demo app works, because it includes the swift files in the repo.  Might be good to show an example Podfile though.

**Comment by Jon-Schneider** [comment]
Thanks for reaching out! I just updated the project to 0.4.1, which updates the Demo project to use a pod file instead of direct file reference. I didn't know until I went and checked that ```pod try [PodName]``` will actually run ```pod install``` on your demo project, which was the reason I originally directly included the library.
